ingest:
  nameOverride: ""
  fullnameOverride: ""
  labels: {}
  image:
    repository: containeryard.evoforge.org/warehouses/datawave/ingest-dev 
    tag: 3.40.0-SNAPSHOT
    pullPolicy: Always
    pullSecrets: []
  deployment:
    replicaCount: 1
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    datawaveVersion: 3.40.0-SNAPSHOT