{{- define "datawave.yumrepo" -}}
[Artifactory]
name=Artifactory
baseurl=https://datawave-token:eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJNM2xWbG1WM1JScHhlaUxPOGkxd1A0b1ZDbmptb1dqMmtoSGF4MU4weTBjIn0.eyJzdWIiOiJqZnJ0QDAxZjI0cXlueWoyaDl5MXJqbjRyNGsweDkzXC91c2Vyc1wvZGF0YXdhdmUtdG9rZW4iLCJzY3AiOiJtZW1iZXItb2YtZ3JvdXBzOmRhdGF3YXZlIGFwaToqIiwiYXVkIjoiamZydEAwMWYyNHF5bnlqMmg5eTFyam40cjRrMHg5MyIsImlzcyI6ImpmcnRAMDFmMjRxeW55ajJoOXkxcmpuNHI0azB4OTNcL3VzZXJzXC9hbGxldmluIiwiaWF0IjoxNjMxNzk2NDIyLCJqdGkiOiIxOGZkNDcwOS1iYjA1LTQwNDQtYjdiNi1mYzEzMTM2NmI4NzEifQ.b6F9h4QND0L0-wk1satdrQKxdFTtqjH2fltWWw63xzXNDPEUAM5ZQ0Z2wDdCoZAWvmxTARXebCc7NPrMpYyXO8yx0VfUZPykl0SZ4Za_bhio72yt_2S1H-kzgHAQeZbB0Jnk0zOOpwckBUxUQMHvVmILk26XlCtJGA2rw8Ox2DER93S9MDuJ0D-oNHqYdsG-I796omxHM244b00Ld3CfDuHZ78xcKTWkmvdF-264S0k2qY8TYGCB37p51i-jvcupPLtq5WOHhsRHMo_Hp7bwGB0ICeEd3EYtOc1tfWfKoeDV6hUZ_FRYV4XILlXO_3APuQ-mjUNlRlJAmwoiPYucHw@artifactory.adv.evoforge.org/artifactory/datawave-rpm-local/
enabled=1
gpgcheck=0
sslverify=false


{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datawave.fullname" . }}-repo
  labels:
    {{- include "datawave.labels" . | nindent 4 }}
type: Opaque
data:
  artifactory.repo: {{ include "datawave.yumrepo" . | b64enc }}
