####################################
# Core Helm Template Configuration #
####################################

apiVersion: v1
kind: Secret
######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Chart.Name }}-{{ .Values.web.certificatesSecret.meta.name }}"
type: Opaque
##########################
# Configuration Map Data #
##########################

data: 
  keystore.p12: |-
{{ .Files.Get "keystore.p12" | b64enc | indent 4 }}
  truststore.jks: |-
{{ .Files.Get "truststore.jks" | b64enc |  indent 4}}