####################################
# Core Helm Template Configuration #
####################################

apiVersion: networking.k8s.io/v1
kind: Ingress

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Chart.Name }}-docs-ingress"
  annotations:


####################################
# Ingress Controller Specification #
####################################

spec:

  ################################################
  # Transport-Layer Security (TLS) Configuration #
  ################################################

  tls:
    - hosts:
        - "{{ .Values.web.ingress.services.domain }}"
      secretName: datawave-tls

  #########################################
  # Ingress Controller Rule Configuration #
  #########################################
  ingressClassName: nginx
  rules:
    - host: "{{ .Values.web.ingress.services.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.web.docsService.meta.name }}"
                port: 
                  number: {{ .Values.web.docsService.port }}
